kifuan/helang

README.MD

何语言 Kotlin 脚本版

---

README.MD

没有莲宝我不是很支持😡

---

README.MD

然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵然然你带我走吧然然，没有你我怎么活啊然然😭😭🤤🤤🥵🥵

关注嘉然然顿顿解馋馋

---

README.MD

关注星瞳送溜溜梅！关注星瞳送溜溜梅！关注星瞳送溜溜梅！

---

helang/speed_tester.py

自动释放5G测试所消耗的磁盘空间
通过万能的print字符串的形式实现

feat:delete test files

---

README.MD

feat: C# impl

---

helang/check_cyberspaces.py
requirements.txt
setup.cfg

如果只有这一处网络请求，没必要用requests。如果未来还打算加更多的，可以考虑留着

Remove requests

---

README-RU.MD
README.MD

`HeScript` 强势上线！
[hescript](https://github.com/Rotten-LKZ/hescript)

chore: update readme

---

README-EN.MD
README-RU.MD
README.MD

Co-authored with @SherkeyXD
Very good translation, love from 瓷器

English README Translation

---

README-EN.MD

readme: intentional typo to show loyalty to He

---

README-EN.MD

注意看，这个中国小哥一小时开了三个PR
反转了，原来我才最不尊重何捏😨😥😨😭

readme: fix the link to ArchLinux

---

README-EN.MD

readme: en translation (print logo)

---

LICENSE

修改LICENSE里的英文表达

---

README.MD
helang/check_cyberspaces.py

Temporary mitigation measures that do not support IPv6
不支持IPv6的临时缓解措施
This problem needs to be solved in the future
这个问题需要在将来解决

feat: temporary mitigation measures

---

helang.cpp

refactor: 为cpp版实现提高性能

---

README.MD
helang/launch.py

**Saint He** is tolerant
**Saint He** 是宽容的

feat: add a startup method

---

README.MD

README: Add OCaml

---

helang.cpp

fix a build bug

---

README-EN.MD
README.MD

最后一次更新，然后就准备 XDU 的线上教学啦。感谢这个 repo 和 @kifuan 能让我们玩！非常大的 ❤️ ！

readme: final en translation updates

---

README-EN.MD
README-RU.MD
README.MD

增加二创：C++ 模板元编程实现——何而上语言（Meta-Helang）

readme: add C++ Metaprogramming version - Meta-Helang

---

helang/lt_code/runner.py

修改不恰当的import顺序
